#+TITLE: Chapter 2: Rule Based Carry and Momentum Investment

This chapter is about the effectiveness of applying simple rules to
the carry investment. The carry trade will be defined, a "benchmark"
established, and finally rule based carry strategies will be discussed
to improve returns and reduce risk.

A *carry trade* broadly means receiving returns from holding (/going
long/) on asset against borrowing (/shorting/) another asset. An example
with interest rates: Borrow at low rates and lend or receive long-term
rates such as 30-year rates, assuming an upward sloping yield
curve. This is known as a *positive carry* because the net position is
profitable to hold. The inverse position of receiving short-term rates
and paying long-term rates is *negative carry* because it is held at a
loss. Negative carry, similar to shorting a stock, is a speculative
high-risk strategy where the expectation of a dramatic repricing of
assets would compensate for the losses of passively holding an
unprofitable position. The chapter focuses on the positive carry.

In financial markets, carry trade is generally understood to refer to
investments in currency markets in which you borrow in currencies with
low interest rates to buy and hold different currencies with high
interest rates. It is essentially interest rate arbitrage between
currency pairs. The investment will be profitable as long as target
currency does not weaken against funding currency too greatly to erase
the interest rate differential.

* "Benchmark" Returns in the FX Carry Trade

A benchmark currency carry investment is needed to illustrate in
greater detail the profitability vs the risk of investing in the
simplest form of the carry strategy.

The *rule* is that one the monthly basis, you create an equally weighted
basket such that if the interest rate of the foreign currency is
higher than the US rate, you borrow 1 USD and buy and hold the foreign
currency for a month. If the interest rate of the foreign currency is
lower than the US rate, you borrow 1 USD worth of foreign currency and
buy and hold the USD for a month. You receive the net interest rates
for holding the position.

From January 2001 to June 2013, 6 out of the 9 currency carry trades
in the book outperformed the S&P 500. The Sharpe ratio of the returns
are higher and the returns are less skewed (where skew tells us that
if the market goes down, the value of an asset also goes down to an
even greater degree). Moreover, returns of carry trades are relatively
uncorrelated with returns from other risky assets such as the S&P 500.

* The Risks of the FX Carry Trade

[[https://www.youtube.com/watch?v=fpK36FZmTFY][What risks? We didn't see any risks, did we Charlie?]]
